Feature: specify grafana organisation for client
panodata/grafana-client pull request #127
Opened 2023-10-27 06:22 UTC by lilatomic

## Description
Adds awareness of Grafana Orgs. This allows requests to be made against a specific org instead of the "current" org of the user.
fixes #126 

Implemented using the "X-Grafana-Org-Id" header [docs](https://grafana.com/docs/grafana/latest/developers/http_api/auth/?plcmt=learn-nav#x-grafana-org-id-header).

I didn't find a doc that looked like a place to document this feature. Where do you think it should go? or is the arg list good enough?

## Checklist

- [x] The patch has appropriate test coverage
- [x] The patch follows the style guidelines of this project
- [x] The patch has appropriate comments, particularly in hard-to-understand areas
- [ ] The documentation was updated corresponding to the patch
- [x] I have performed a self-review of this patch

2023-10-27 06:39 UTC, amotl commented
> I didn't find a doc that looked like a place to document this feature. Where do you think it should go? or is the arg list good enough?

Effectively, there is only the main README, so it should go between "[Authentication](https://github.com/panodata/grafana-client#authentication)" and "[Timeout settings](https://github.com/panodata/grafana-client#timeout-settings)", with a headline like "Configure Organization".

Let's directly refer to https://grafana.com/docs/grafana/latest/developers/http_api/auth/#x-grafana-org-id-header over there, and cite the resource like

When using the `organization_id` parameter to `GrafanaClient`, its value will be populated into the `X-Grafana-Org-Id` HTTP request header.

> [It] is an optional property that specifies the organization to which the action is applied. If it is not set, the created key belongs to the current context org. Use this header in all requests except those regarding admin.

2023-10-27 06:43 UTC, amotl requested changes
Thank you very much. Can I ask you to add a little section about the feature to the README file?

2023-10-27 13:52 UTC, amotl commented
Wait.

> The `X-Grafana-Org-Id?  HTTP request header is an optional property that specifies the organization to which the action is applied. If it is not set, **the created key** belongs to the current context org. **Use this header in all requests except those regarding admin.**

I've re-read the statement and stumbled upon the highlighted fragments. Is it possible that this header is only meant to designate the organization identifier when creating authentication tokens? Coming from that insight, is it possible that authentication tokens are only meant to work within the context of a single organization, i.e. they are implicitly bound to an organization, and can't be used cross-organization?

I have to admit that I am not familiar with those concerns of the Grafana API, so I am humbly asking for education on this matter. Also, did you verify that your change works as intended for you? Are _you_ using it to successfully run requests to a real Grafana instance, impersonating different organizations?

2023-10-29 20:47 UTC, lilatomic commented
I've tested this manually a bit and wrote up the following test (we can add it when we get integration tests):
```sh
docker run --rm -p 3000:3000 grafana/grafana:10.1.5
```
```python

def mk_gfn(organization_id):
    return GrafanaApi(("admin", "admin",), "localhost", 3000, organization_id=organization_id)


def mk_org(g: GrafanaApi) -> int:
    return g.organization.create_organization({"name": str(random.randint(0, 10000))})["orgId"]


def test_org_multiple_with_header():
    """Test that multiple instances of GrafanaApi will interact with the correct Org"""
    # Create a GrafanaApi with no org and create a new org
    g = mk_gfn(None)
    org1_id = mk_org(g)
    org2_id = mk_org(g)

    # Create GrafanaApis in both orgs
    g1 = mk_gfn(org1_id)
    g2 = mk_gfn(org2_id)

    # Create resources in org1 and check that only org1 can see them
    g1.dashboard.update_dashboard({"dashboard": {"title": "d1"}})
    r1 = g1.search.search_dashboards(type_="dash-db")
    print("dashboards in org1", r1)
    assert len(r1) == 1
    r2 = g2.search.search_dashboards(type_="dash-db")
    print("dashboards in org2", r2)
    assert len(r2) == 0


def test_org_header_ignores_context():
    """Test that a GrafanaApi bound to an Org is not affected by changing the current Org context"""
    g = mk_gfn(None)
    org1_id = mk_org(g)

    # Create resources in org1
    g1 = mk_gfn(org1_id)
    g1.dashboard.update_dashboard({"dashboard": {"title": "d1"}})
    r1 = g1.search.search_dashboards(type_="dash-db")
    print("dashboards in org1", r1)
    assert len(r1) == 1

    # switch current context to main org
    g.user.switch_actual_user_organisation(1)

    # verify org1 GrafanaApi is still bound to org1
    r1 = g1.search.search_dashboards(type_="dash-db")
    print("dashboards in org1", r1)
    assert len(r1) == 1

```

2023-10-29 21:20 UTC, lilatomic commented
Thanks for outlining the documentation you'd like to see. I've done the writeup, if you're happy with it we should be good to merge!

2023-10-30 07:22 UTC, amotl approved these changes
Thank you very much.

2023-10-30 07:23 UTC, merged

2023-10-31 03:53 UTC, lilatomic commented
You're welcome! It was a pleasure working with you, and I want to thank you for your continued maintenance of this library!

2023-11-01 03:05 UTC, amotl commented
Do you already know about grafana-client's sister package, [grafana-wtf](https://github.com/panodata/grafana-wtf)? If that resonates with you, and you will come up with ideas for features yet missing, we will be all ears.