feat: allow updating the folder UID
panodata/grafana-client pull request #32
Opened 2022-08-09 21:24 UTC by iNoahNothing

Signed-off-by: Noah Krause <krausenoah@gmail.com>

## Description

Updates the `update_folder` method of the `folder` API to allow changing the UID of the folder.

Just adding an additional argument to the method was done for backwards compatibility. Passing in a dictionary of the folder elements to be changed would have been a preferred solution to support the upstream API long-term.

## Checklist

- [x] The patch has appropriate test coverage
- [x] The patch follows the style guidelines of this project
- [x] The patch has appropriate comments, particularly in hard-to-understand areas
- [x] The documentation was updated corresponding to the patch
- [x] I have performed a self-review of this patch

2022-08-12 11:27 UTC, amotl requested changes
Dear Noah,

thanks a stack for your contribution. I will share my thoughts within this post and some inline comments.

> Passing in a dictionary of the folder elements to be changed would have been a preferred solution to support the upstream API long-term.

Maybe true. But when looking at the documentation [1], I think not many more request body fields will be added in the future, so I think it will be fine to extend the current version of the client-side API method for that purpose of adding the missing `new_uid` field, to be used as

> **uid** – Provide another [unique identifier](https://grafana.com/http_api/folder/#identifier-id-vs-unique-identifier-uid) than stored to change the unique identifier.

> Just adding an additional argument to the method was done for backwards compatibility. 

I think that is fine. However, when you will look at the method signature, you will recognize that people **might** be using the method with `title` as a _positional_ argument. On that matter, I am humbly asking you to add the `new_uid` argument at the end of the argument list instead. Do you have any objections?

With kind regards,
Andreas.

[1] https://grafana.com/docs/grafana/latest/developers/http_api/folder/#update-folder

2022-08-12 11:27 UTC, amotl commented on grafana_client/elements/folder.py
> +    def update_folder(self, uid, new_uid=None, title=None, version=None, overwrite=False):
```suggestion
    def update_folder(self, uid, title=None, version=None, overwrite=False, new_uid=None):
```

2022-08-12 11:27 UTC, amotl commented on grafana_client/elements/folder.py
> +        print(body)
Can you remove that `print` statement?

2022-08-12 11:27 UTC, amotl commented on grafana_client/elements/folder.py
> +        print(r)
Can you remove that `print` statement?

2022-08-12 11:27 UTC, amotl commented on test/elements/test_folder.py
> +            title="Departmenet DEF", uid="nErXDvCkzz", new_uid="nErXDvCkzz", version=1, overwrite=True
Maybe we can use a different value for the `new_uid` argument here in order to better demonstrate its purpose?
```suggestion
            title="Departmenet DEF", uid="nErXDvCkzz", new_uid="oFsYEwDlaa", version=1, overwrite=True
```

2022-08-12 11:27 UTC, amotl commented on test/elements/test_folder.py
> +        self.assertEqual(folder["uid"], "nErXDvCkzz")
Wouldn't this work already?
```suggestion
        self.assertEqual(folder["uid"], "oFsYEwDlaa")
```

2022-09-14 22:23 UTC, amotl commented
Dear Noah,

I've converged your patch into #34, with some minor adjustments. Thank you again.

With kind regards,
Andreas.

2022-09-14 22:23 UTC, closed without merging

2022-09-15 13:48 UTC, iNoahNothing commented
Thanks @amotl! My apologies for dropping the ball on responding to your review but glad to see the improvements make it to the client!