introduced function get_dashboard_by_name
panodata/grafana-client pull request #9
Opened 2022-02-09 12:02 UTC by luixx

## Description
there is the new function get_dashboard_by_name introduced so the dashboards can be found by name and not only id

## Checklist

- [ ] The patch has appropriate test coverage
- [ ] The patch follows the style guidelines of this project
- [ ] The patch has appropriate comments, particularly in hard-to-understand areas
- [ ] The documentation was updated corresponding to the patch
- [ ] I have performed a self-review of this patch

2022-02-09 14:36 UTC, amotl commented
Dear @luixx,

thanks a stack for your contribution. Do you believe you can add a corresponding test case?

With kind regards,
Andreas.

2022-02-09 16:11 UTC, luixx commented
> Dear @luixx,
> 
> thanks a stack for your contribution. Do you believe you can add a corresponding test case?
> 
> With kind regards, Andreas.

Hi,  first i have to figure out how this works but then i can do this (never did this here before). 
Greetings Karsten

2022-02-09 17:49 UTC, amotl requested changes

2022-02-09 17:49 UTC, amotl commented on grafana_client/elements/dashboard.py
> +        r = self.api.GET(get_dashboard_path)
Hi Karsten,

the test case you added croaks on this line with `AttributeError: 'Dashboard' object has no attribute 'api'`, see [^1]. While refactoring the package, we slightly changed its internals, so on this spot, `self.api` became `self.client`:

```suggestion
        r = self.client.GET(get_dashboard_path)
```

Can you amend your patch correspondingly? If anything goes right after that, the tests should succeed. In order to verify it, you can run the test suite on your workstation, like documented in the README at [^2].

With kind regards,
Andreas.

[^1]: https://github.com/panodata/grafana-client/runs/5128322276
[^2]: https://github.com/panodata/grafana-client#software-tests

2022-02-10 10:04 UTC, luixx commented
So, i hope everything is fine now.

2022-02-10 12:55 UTC, amotl commented
> So, i hope everything is fine now.

Excellent. Thank you again!

2022-02-10 13:19 UTC, merged

2022-03-16 22:11 UTC, amotl commented
Dear Karsten,

we just relased `grafana-client==2.2.0`, including your contribution. Thank you again!

With kind regards,
Andreas.